services:
  
  auth-service:
    image: alexdev93/auth-service:latest
    ports:
      - "9090:9090" # adjust based on your app's exposed port
    # environment:
      # - NODE_ENV=production
      # - JWT_SECRET=your-secret
      # - DB_URI=mongodb://mongo:27017/auth-db
      # - REDIS_URL=redis://redis:6379

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
