spring:
  application:
    name: myapp
  data:
    mongodb:
      uri: mongodb+srv://alemayehudev:blazeog01369@cluster0.b9wba.mongodb.net/auth-service?retryWrites=true&w=majority&appName=Cluster0
      authentication-database: admin # Optional: Specify if using a different authentication database
      connection-pool:
        min-size: 5 # Optional: Minimum connection pool size
        max-size: 20 # Optional: Maximum connection pool size
        max-wait-time: 1000ms # Optional: Maximum wait time for a connection from the pool

  cache:
    type: redis
    redis:
      host: redis-18449.c245.us-east-1-3.ec2.redns.redis-cloud.com
      port: 18449
      timeout: 1000ms
      password: up8GMRDvob3Sng4kohON96hQdeTzNmBT
      ssl: false
      time-to-live: 60000ms
      cache-null-values: false

  mail:
    host: smtp.your-email-provider.com # SMTP server host
    port: 587 # or 465 for SSL
    username: your-email@example.com # Your email address
    password: your-email-password # Your email account password
    properties:
      mail:
        smtp:
          auth: true # Enable authentication
          starttls:
            enable: true # Enable STARTTLS
            required: true # Require STARTTLS
    default-encoding: UTF-8 # Default encoding for emails

  actuator:
    endpoints:
      web:
        exposure:
          include: "*" # Expose all actuator endpoints

management:
  endpoints:
    web:
      exposure:
        include: "*" # Ensure actuator endpoints are accessible
  prometheus:
    metrics:
      export:
        enabled: true # Enable Prometheus metrics export
  health:
    defaults:
      enabled: true # Enable default health indicators
    mongodb:
      enabled: true # Enable MongoDB health check
    redis:
      enabled: true # Enable Redis health check

logging:
  level:
    root: INFO # Set the root logging level to INFO
    "[org.springframework.boot.actuate]": DEBUG # Set logging level for Actuator to DEBUG
    "[org.springframework.data.mongodb.core]": DEBUG # Set logging level for MongoDB operations to DEBUG

server:
  port: 8083
